baseURL: http://something-fresh.org/
languageCode: en-us
title: Hugo Fresh Theme
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/ds.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Next Gen Data Annotation Solutions
    # Hero subtitle (optional)
    subtitle: The future of data and web base solutions is here.. 
    # Button text
    buttontext: Contact Us
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/cover.svg
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Services
    id: 'servicebtn'
  - title: Contact us
    button: true

  section1:
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App Development
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: /
      # buttonText: Free trial
    - title: Annotation Solutions
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: /
      # buttonText: Get started
    - title: Static Websites
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      # buttonText: Get started

  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Data Annotation Solutions
      text: Our company offers more secure and accurate data labelling services to our clients. Train and validate our company human annotators in your ML (Machine Learning) model. Currently we provide services for image annotation/ image labelling and video annotations/ video labelling.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: segmentation
    - title: Images Annotation
      text: Image annotation/ Image labelling services includes bounding boxes annotations, Keypoints annotations, Polygons annotations, 3D cuboids annotations, LIDAR segmentations and Images Classifications by tags.
      icon: annotation
    - title: Videos Annotation
      text: Video annotation services includes moving bounding boxes, objects tracking and LIDAR annotations, Segmentation.
      icon: video_ann

  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3

  section5: true

  footer:
    # Logo (from /images/logos/___)
    logo: ds.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    # quicklinks:
    #   column1:
    #     title: "Product"
    #     links:
    #     - text: Discover features
    #       link: /
    #     - text: Why choose our product?
    #       link: /
    #     - text: Compare features
    #       link: /
    #     - text: Our roadmap
    #       link: /
    #     - text: AGB
    #       link: /agb
    #   column2:
    #     title: "Docs"
    #     links:
    #     - text: Get started
    #       link: /
    #     - text: User guides
    #       link: /
    #     - text: Admin guide
    #       link: /
    #     - text: Developers
    #       link: /
    #   column3:
    #     title: "Blog"
    #     links:
    #     - text: Latest news
    #       link: /blog/first
    #     - text: Tech articles
    #       link: /blog/second
